config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bikes do
   resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:show] do
    resources :bookings, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
  BIKE_STYLE = ['VTC', 'VTT', 'Vélo de ville']
  BIKE_COLOR = ['Argenté', 'Blanc', 'Bleu', 'Doré', 'Gris', 'jaune', 'Orange', 'Rouge', 'Vert']
  BIKE_GENDER = ['Homme', 'Femme']
  BIKE_CITY = ['Nantes', 'Rennes', 'Lorient', 'Vannes', 'Arradon', 'Arzon', 'Sarzeau', 'Baden', 'Bono', 'Carnac', 'La Trinité sur mer']
  belongs_to :user
  has_many_attached :photos
  has_many :reviews

  validates :model, presence: true
  validates :address, presence: true
  validates :gender, presence: true
  validates :color, presence: true
  validates :gear, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :style, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: :address,
    using: {
      tsearch: { prefix: true }
    }
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  validates :bike_id, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :total_price, presence: true

  # include PgSearch::Model
  # pg_search_scope :global_search,
  #   against: [ :start_date, :end_date ],
  #   associated_against: {
  #     bike: :address
  #   },
  #   using: {
  #     tsearch: { prefix: true }
  #   }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :bike
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :username, presence: true
  validates :username, uniqueness: true
  has_many :reviews
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :find_bike, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:home, :index, :show]

  def index
    if params[:query].present?
      @bikes = policy_scope(Bike).geocoded.search_by_address(params[:query]).order(updated_at: :desc)
      @markers = @bikes.map do |bike|
        {
          lat: bike.latitude,
          lng: bike.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { bike: bike }),
          image_url: helpers.asset_url("bike")
        }
      end
    else
      @bikes = policy_scope(Bike).geocoded.order(updated_at: :desc)
      @markers = @bikes.map do |bike|
        {
          lat: bike.latitude,
          lng: bike.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { bike: bike }),
          image_url: helpers.asset_url("bike")
        }
      end
    end
  end

  def new
    @bike = Bike.new
    authorize @bike
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user
    authorize @bike
    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new
    end
  end

  def show
    @bike = Bike.find(params[:id])
    @booking = Booking.new
    authorize @bike
  end

  def destroy
    @bike = Bike.find(params[:id])
    authorize @bike
    @bike.destroy
    redirect_to bikes_path
  end

  def edit
  end

  def update
    @bike.update(bike_params)

    redirect_to bike_path(@bike)
  end

  private

  def bike_params
    params.require(:bike).permit(:model, :address, :gender, :color, :gear, :description, :price, :style, photos: [])
  end

  def find_bike
    @bike = Bike.find(params[:id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # skip_after_action :verify_authorized, only: [:index]
  def index
    @bookings = policy_scope(Booking)
  end

  def new
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new
    authorize @booking
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def create
    @bike = Bike.find(params[:bike_id])
    @booking = Booking.new(booking_params)
    @booking.bike = @bike
    nb_days = (@booking.end_date - @booking.start_date).to_i
    @booking.total_price = nb_days * @bike.price
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bike_path(@booking.bike)
  end


  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

  def find_booking
    @booking = booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
    @review.bike = @booking.bike
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.bike = @booking.bike
    @review.user = current_user
    authorize @review

    if @review.save
      redirect_to bike_path(@booking.bike)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<div class="main-container">
  <div class="popup">
    <h2><%= bike.address %></h2>
      <p><%= bike.model %></p>
  </div>
</div>

app/views/bikes/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1>Modifier mon vélo</h1>
    <div class="col-4">
      <%= simple_form_for @bike do |f| %>
        <%= f.input :model %>
        <%= f.input :address %>
        <%= f.input :gender %>
        <%= f.input :color %>
        <%= f.input :gear %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :style %>
        <%= f.submit "Valider", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/bikes/index.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523891046626-daa31d9e280f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);
  background-size: cover">
  <div class="container">
    <div class="row">
      <div class="col-7">
        <div class="main-container">
          <div class="cards">
            <% @bikes.each do |bike| %>
              <%= link_to bike_path(bike) do %>
                <div class="card-bike">
                  <% bike.photos.each do |photo| %>
                    <%= cl_image_tag photo.key, crop: :fill %>
                  <% end %>
                  <div class="card-bike-infos">
                    <div class="d-flex flex-column justify-content-between">
                      <h2><%= bike.model %></h2>
                      <p><%= bike.address %></p>
                    </div>
                    <div style="position: relative; top: 40px">
                      <h2 id="card-bike-price"><%= bike.price %>€</h2>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-5">
        <div id="map"
         style="width: 100%; height: 75vh; margin: 12px 0 12px 0; position: sticky; top: 13.6vh"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        <div style="position: sticky; top: 90vh; margin: 12px 0 12px 0">
          <%= form_tag bikes_path, method: :get do %>
            <div class="form-inline ml-5 mt-2 mb-2">
              <div class="form-group">
                <%= text_field_tag :query,
                  params[:query],
                  class: "form",
                  placeholder: "Où cherchez-vous?"
                %>
              </div>
              <div class="form-group ml-3">
                <%= submit_tag "Pédaler!", class: "btn btn-flat" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="container">
<!--  -->
  <h1 class="title mt-2">Ajouter un vélo</h1>
  <%= simple_form_for @bike do |f| %>
    <div class="row justify-content-center mb-5">
      <div class="col-6">
        <%= f.input :model,label: "Modèle" %>
        <%= f.input :style, collection: Bike::BIKE_STYLE, label: "Type" %>
        <%= f.input :color, collection: Bike::BIKE_COLOR, label: "Couleur" %>
        <%= f.input :description, label: "Description" %>
      </div>

      <div class="col-6">
        <%= f.input :gender, collection: Bike::BIKE_GENDER, label: "Genre" %>
        <%= f.input :gear, label: "Vitesses" %>
        <%= f.input :address, label: "Adresse", class: 'bike_new_id' %>
        <%= f.input :price, label: "Prix" %>
        <%= f.input :photos, as: :file, input_html: { multiple: true} %>
      </div>
      <div>
        <%= f.submit "Valider", class: 'btn btn-flat' %>
      </div>
    </div>
  <% end %>
</div>

app/views/bikes/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
      <div class="card-show-top">
        <h2 class="my-3"><%= @bike.model %></h2>
        <hr>
        <div class="infos d-flex justify-content-between my-3">
          <div class="note">
            <p class="mb-0"><i class="far fa-star"></i> 4 - 8 locations - <%= @bike.address %></p>
          </div>
          <div class="share d-flex justify-content-between align-items-center">
            <%= link_to(bike_path(@bike),
              method: :delete,
              data: { confirm: "Voulez-vous vraiment supprimer votre annonce?"}) do %>
              <i class="fas fa-trash-alt pr-3"></i>
            <% end %>
            <i class="fas fa-share-alt pr-3"></i>
            <i class="far fa-bookmark pr-3"></i>
          </div>
        </div>
        <div class="card-velo">
          <% @bike.photos.each do |photo| %>
            <%= cl_image_tag photo.key, crop: :fill %>
        <% end %>
        </div>
        <div class="bike-infos d-flex">
            <div class="col-md-7 ml-2">
              <div class="row">
                <div class="col-md-4 d-flex flex-column px-2 py-3">
                  <p class="p-1"><i class="fas fa-restroom"></i> Type : <%= @bike.gender %></p>
                  <p class="p-1"><i class="fas fa-bicycle"></i> Style : <%= @bike.style %></p>
                </div>
                <div class="col-md-4 d-flex flex-column px-2 py-3">
                  <p class="p-1"><i class="fas fa-palette"></i> Couleur : <%= @bike.color %></p>
                  <p class="p-1"><i class="fas fa-cog"></i> Vitesses : <%= @bike.gear %></p>
                </div>
                <div class="col-md-4 px-2 py-3 d-flex align-items-center">
                  <p class="p-1 d-flex align-items-center"><i class="fas fa-user-circle pr-2" id="loueur_icone"></i> Loueur : <%= @bike.user.first_name %> </p>
                </div>
              </div>
              <div class="row">
                <div class="description px-3">
                  <p><%= @bike.description %></p>
                </div>
              </div>
            </div>
            <div class="col-md-5">
              <div class="row">
                <div class="booking w-100">
                  <strong><%= @bike.price %>€</strong> par jour
                  <p>Ajouter vos dates</p>
                  <%= simple_form_for([@bike, @booking]) do |f| %>
                    <div class="row">
                      <div class="col">
                        <%= f.input :start_date, label: "Arrivée", placeholder: Time.zone.now.strftime("%b %d, %Y"), as: :string, input_html: {class: "datepicker", id: "range_start"}  %>
                      </div>
                      <div class="col">
                        <%= f.input :end_date, label: "Départ", placeholder: Time.zone.now.strftime("%b %d, %Y"), as: :string, input_html: {class: "datepicker", id: "range_end"}  %>
                      </div>
                    </div>
                      <%= f.submit "Réserver" , class:"btn btn-flat" %>
                  <% end %>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5">
  <div class="row d-flex justify-content-center">
    <div class="col-10">
      <h3>Evaluations</h3>
      <div class="reviews-total col-12 px-2 py-3 d-flex flex-column justify-content-center">
        <% @bike.reviews.each do |review| %>
          <div class="review-card">
            <div class="reviewss d-flex align-items-center w-100">
<!--               <div class="avatar pr-3">
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar-large", alt: "avatar-large" %>
              </div> -->
              <div class="text-review d-flex justify-content-between w-100">
                <div class="review pl-5 "><%= review.content %></div>
                <div class="date d-flex justify-content-end"><%= review.created_at.strftime("%b %d, %Y") %></div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--   <div class="row">
    <div class="reviews-total col-12 px-2 py-3">
      <h3>Evaluations</h3>
      <div class="p-1"><p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i> 8 locations</p></div>
      <div class="row">

        <div class="reviews d-flex align-items-center w-100">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar-large", alt: "avatar-large" %>
          <div class="avatar pr-3">
          </div> -->
   <!--        <div class="text-review d-flex justify-content-between w-100">
            <div class="review pl-3 ">Parfait ce vélo !</div>
            <div class="date d-flex justify-content-end">1/4/2020</div>
          </div>
        </div>
        <div class="reviews d-flex align-items-center w-100">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar-large", alt: "avatar-large" %>
          <div class="avatar pr-3">
          </div>
          <div class="text-review d-flex justify-content-between w-100">
            <div class="review pl-3 ">En bon état, nous a suivi pendant tout notre tour du golf ! Je recommande</div>
            <div class="date d-flex justify-content-end">15/03/2020</div>
          </div>
        </div>
        <div class="reviews d-flex align-items-center w-100">
          <%#= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar-large", alt: "avatar-large" %>
          <div class="avatar pr-3">
          </div>
          <div class="text-review d-flex justify-content-between w-100">
            <div class="review pl-3 ">Loueur très sympathique et vélo en parfait état. Pour des vacances avec style.</div>
            <div class="date d-flex justify-content-end">9/02/2020</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
 -->

app/views/bookings/index.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523891046626-daa31d9e280f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);
  background-size: cover">
  <div class="container", style="min-height: 88vh">
    <div class="row justify-content-center">
      <div class="col-8">
        <% @bookings.each do |booking| %>
          <div class="card-product mb-3 mt-3">
            <%= cl_image_tag booking.bike.photos.first.key %>
            <div class="card-product-infos">
              <h2> <%= booking.bike.model %> </h2>
              <p><strong>Date de début</strong>: <%= booking.start_date.strftime("%A, %b %d") %></p>
              <p><strong>Date de fin</strong>: <%= booking.end_date.strftime("%A, %b %d") %></p>
              <p><strong>Tarif</strong>: <%= booking.total_price %>€</p>
              <p><strong>Propriétaire</strong>: <%= booking.bike.user.first_name %></p>
              <%= link_to "Donner votre avis", new_booking_review_path(booking), class: "btn btn-flat mt-3" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-center">
        <div class="formulaire mb-3 form-row" style="width: 500px">
          <%= simple_form_for([@bike, @booking]) do |f| %>
            <div class="row">
              <div class="col">
                <%= f.input :start_date, as: :string, input_html: {class: "datepicker", id: "range_start"}  %>
              </div>
              <div class="col">
                <%= f.input :end_date, as: :string, input_html: {class: "datepicker", id: "range_end"}  %>
              </div>
            </div>
              <%= f.submit "Réserver" , class:"btn btn-flat" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="d-flex justify-content-center">
        <div class="card-booking p-3 mt-3 mb-3">
          <h3>Ma réservation</h3>
          <% @booking.bike.photos.each do |photo| %>
            <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <div class="card-booking-infos mt-2">
            <div class="d-flex flex-column align-content-between">
              <p><strong>Date de début</strong>: <%= @booking.start_date.strftime("%A, %b %d") %></p>
              <p><strong>Date de fin</strong>: <%= @booking.end_date.strftime("%A, %b %d") %></p>
            </div>
            <h3 class="">Prix total: <strong><%= @booking.total_price %>€</strong></h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeMeUp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="alert"><%= alert %></p>
    <div class="decal">
      <%= yield %>
    </div>
    <%= render 'shared/footers' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1523891046626-daa31d9e280f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <div class="row d-flex flex-column align-items-center">
      <div class="col-md-8">
        <div class="d-flex flex-column align-items-center">
          <h1>Bike me <strong>UP</strong>!</h1>
          <p>Louez un vélo à <span id="banner-typed-text"></span>.</p>
        </div>
        <div class="d-flex justify-content-center mt-3">
          <%= form_tag bikes_path, method: :get do %>
          <div class="form-inline ml-5">
            <div class="form-group">
              <%= text_field_tag :query,
                params[:query],
                class: "form",
                placeholder: "Où cherchez-vous?"
              %>
            </div>
            <div class="form-group ml-3">
              <%= submit_tag "Pédaler!", class: "btn btn-flat" %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1 class="title mt-2">Donner votre avis</h1>

<%= simple_form_for([ @booking, @review ]) do |f| %>
  <%= f.input :content, as: :text %>
  <%= f.button :submit, class: "btn btn-flat mb-3" %>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footers.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5">

  <div style="background-color: #099C68;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0" style="color: white;">
          <h6 class="mb-0">Restez en contact avec nous!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a class="fb-ic">
            <i class="fab fa-facebook-f text-white mr-4" style="font-size: 21px;"></i>
          </a>
          <!-- Twitter -->
          <a class="tw-ic">
            <i class="fab fa-twitter text-white mr-4" style="font-size: 21px;"></i>
          </a>
          <!--Linkedin -->
          <a class="li-ic">
            <i class="fab fa-linkedin-in text-white mr-4" style="font-size: 21px;"></i>
          </a>
          <!--Instagram-->
          <a class="ins-ic">
            <i class="fab fa-instagram text-white" style="font-size: 21px;"></i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4" style="color: gray;">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold">Bike me UP</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Louez un vélo où que vous soyez!
          Bike me UP vous propose de louer votre vélo directement à un particulier.
        </p>

      </div>
      <!-- Grid column -->



      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4" style="color: gray;">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold">Liens Utiles</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;" >
        <p>
          <a class="dark-grey-text" style="color: gray;" href="#!">Votre compte</a>
        </p>
        <p>
          <a class="dark-grey-text" style="color: gray;" href="#!">Service Clients</a>
        </p>
        <p>
          <a class="dark-grey-text" style="color: gray;" href="#!">Aide</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-5 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-4">
        <div class="contact" style="color: gray;">
        <!-- Links -->
          <h6 class="text-uppercase font-weight-bold">Contact</h6>
          <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <i class="fas fa-home mr-3 "></i> Paris, 75011</p>
          <p>
            <i class="fas fa-envelope mr-3"></i>contact@bikemeup.fr</p>
          <p>
            <i class="fas fa-phone mr-3"></i> 01 23 45 67 88</p>
        </div>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-black-50 py-3">© 2020 Copyright:
    <a class="dark-grey-text" style="color: gray;" href="https://mdbootstrap.com/">bikemeup.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand mt-3" do %>
    <p><i class="fas fa-biking"></i> Bike me <strong>UP</strong></p>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item mr-3">
          <%= link_to "Réserver un vélo", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item mr-3">
          <%= link_to "Ajouter une annonce", new_bike_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <button class="dropdown-toggle", id="navbarDropdown", data-toggle="dropdown" }, aria-haspopup="true", aria-expanded="false">
            Mon espace
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", user_bookings_path(current_user), class: "dropdown-item"  %>
            <%= link_to "Messages", "#", class: "dropdown-item"  %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Inscription", new_user_registration_path, class: "nav-link" %>
        </li>
        <li id="bout" class="nav-item" >
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>